#import "./CellCulturePair.gql"

query getEntries($fetchOptions: EntryFetchOptions!) {
    entries(fetchOptions: $fetchOptions) {
        total
        page
        limit
        results {
            ...EntryParts
        }
    }
}

query getEntry($fetchOptions: EntryFetchOptions!) {
    entry(fetchOptions: $fetchOptions) {
        ...EntryParts
    }
}

query getEntryGroups($fetchOptions: EntryGroupFetchOptions!) {
    getEntryGroups(fetchOptions: $fetchOptions) {
        total
        page
        limit
        results {
            id
            name
        }
    }
}

mutation insertEntry($insertOptions: EntryInsertOptions!) {
    insertEntry(insertOptions: $insertOptions) {
        ...EntryParts
    }
}

mutation updateEntry($updateOptions: EntryUpdateOptions!) {
    updateEntry(updateOptions: $updateOptions) {
        ...EntryParts
    }
}

fragment EntryParts on Entry {
    id
    weight
    weightType
    date
    createdAt
    buyer {
        ...BuyerParts
    }
    cellCulturePair {
        ...CellCultureParts
    }
}
