query GetBuyers($options: BuyerFetchOptions!) {
    buyers(options: $options) {
        page
        pageSize
        totalItems
        totalPages
        results {
            ...BuyerParts
        }
    }
}

mutation InsertBuyer($insertOptions: BuyerInsertOptions!) {
    insertBuyer(options: $insertOptions) {
        ...BuyerParts
    }
}

mutation UpdateBuyer($updateOptions: BuyerUpdateOptions!) {
    updateBuyer(options: $updateOptions) {
        ...BuyerParts
    }
}

mutation DeleteBuyer($deleteOptions: DeleteOptions!) {
    deleteBuyer(options: $deleteOptions) {
        numRows
    }
}

fragment BuyerParts on Buyer {
    id
    name
    address
    contact
    createdAt
    dGroup
}
