query GetBuyers($options: BuyerFetchOptions!) {
    buyers(options: $options) {
        page
        pageSize
        totalItems
        totalPages
        results {
            ...BuyerParts
        }
    }
}

mutation InsertBuyer($options: BuyerInsertOptions!) {
    insertBuyer(options: $options) {
        ...BuyerParts
    }
}

mutation UpdateBuyer($options: BuyerUpdateOptions!) {
    updateBuyer(options: $options) {
        ...BuyerParts
    }
}

mutation DeleteBuyer($options: DeleteOptions!) {
    deleteBuyer(options: $options) {
        numRows
    }
}

fragment BuyerParts on Buyer {
    id
    name
    address
    contact
    createdAt
    dGroup
}
