query GetBuyers($fetchOptions: BuyerFetchOptions!) {
    buyers(fetchOptions: $fetchOptions) {
        total
        page
        limit
        results {
            ...BuyerParts
        }
    }
}

query GetBuyer($fetchOptions: BuyerFetchOptions!) {
    buyer(fetchOptions: $fetchOptions) {
        ...BuyerParts
    }
}

mutation InsertBuyer($insertOptions: BuyerInsertOptions!) {
    insertBuyer(insertOptions: $insertOptions) {
        ...BuyerParts
    }
}

mutation UpdateBuyer($updateOptions: BuyerUpdateOptions!) {
    updateBuyer(updateOptions: $updateOptions) {
        ...BuyerParts
    }
}

mutation DeleteBuyer($deleteOptions: DeleteOptions!) {
    deleteBuyer(deleteOptions: $deleteOptions) {
        ...BuyerParts
    }
}

fragment DataGroupParts on DataGroup {
    id
    name
    description
    createdAt
}

fragment BuyerParts on Buyer {
    id
    name
    address
    contact
    createdAt
    dGroup {
        ...DataGroupParts
    }
}
