query GetCells($options: CellFetchOptions!) {
    cells(options: $options) {
        page
        pageSize
        totalItems
        totalPages
        results {
            ...CellParts
        }
    }
}

query GetUnpairedCells($options: CellParityFetchOptions!) {
    unpairedCells(options: $options) {
        page
        pageSize
        totalItems
        totalPages
        results {
            ...CellParts
        }
    }
}

query GetPairedCells($options: CellParityFetchOptions!) {
    pairedCells(options: $options) {
        page
        pageSize
        totalItems
        totalPages
        results {
            ...CellParts
        }
    }
}

mutation InsertCell($insertOptions: CellInsertOptions!) {
    insertCell(options: $insertOptions) {
        ...CellParts
    }
}

mutation UpdateCell($updateOptions: CellUpdateOptions!) {
    updateCell(options: $updateOptions) {
        ...CellParts
    }
}

mutation DeleteCell($deleteOptions: DeleteOptions!) {
    deleteCell(options: $deleteOptions) {
        numRows
    }
}

fragment CellParts on Cell {
    id
    name
    description
    createdAt
    dGroup
}
