# WARN: Graphql codegen is too dumb to make types from fragments

query GetCellCulturesPairs($options: CellCultureFetchOptions!) {
    cellCulturePairs(options: $options) {
        page
        pageSize
        totalItems
        totalPages
        results {
            id
            createdAt
            cell {
                id
                name
                description
                createdAt
                dGroup
            }
            culture {
                id
                name
                description
                createdAt
                dGroup
            }
            dGroup {
                id
                name
                description
                createdAt
                idMbeGroup
            }
        }
    }
}

query GetAllCellCulturePairs($options: CellCultureFetchOptions!) {
    allCellCulturePairs(options: $options) {
        total
        results {
            id
            createdAt
            cell {
                id
                name
                description
                createdAt
                dGroup
            }
            culture {
                id
                name
                description
                createdAt
                dGroup
            }
            dGroup {
                id
                name
                description
                createdAt
                idMbeGroup
            }
        }
    }
}

mutation InsertCellCulturePair($insertOptions: CellCulturePairIds!) {
    insertCellCulturePair(options: $insertOptions) {
        id
        createdAt
        cell {
            id
            name
            description
            createdAt
            dGroup
        }
        culture {
            id
            name
            description
            createdAt
            dGroup
        }
        dGroup {
            id
            name
            description
            createdAt
            idMbeGroup
        }
    }
}

mutation UpdateCellCulturePair($updateOptions: CellCulturePairUpdateOptions!) {
    updateCellCulturePair(options: $updateOptions) {
        id
        createdAt
        cell {
            id
            name
            description
            createdAt
            dGroup
        }
        culture {
            id
            name
            description
            createdAt
            dGroup
        }
        dGroup {
            id
            name
            description
            createdAt
            idMbeGroup
        }
    }
}

mutation DeleteCellCulturePair($deleteOptions: DeleteOptions!) {
    deleteCellCulturePair(options: $deleteOptions) {
        numRows
    }
}
