query GetCellCulturesPairs($options: CellCultureFetchOptions!) {
    cellCulturePairs(options: $options) {
        page
        pageSize
        totalItems
        totalPages
        results {
            ...CellCultureParts
        }
    }
}

query GetAllCellCulturePairs($options: CellCultureFetchOptions!) {
    allCellCulturePairs(options: $options) {
        total
        results {
            ...CellCultureParts
        }
    }
}

mutation InsertCellCulturePair($options: CellCulturePairIds!) {
    insertCellCulturePair(options: $options) {
        ...CellCultureParts
    }
}

mutation UpdateCellCulturePair($options: CellCulturePairUpdateOptions!) {
    updateCellCulturePair(options: $options) {
        ...CellCultureParts
    }
}

mutation DeleteCellCulturePair($options: CellCulturePairDeleteOptions!) {
    deleteCellCulturePair(options: $options) {
        numRows
    }
}

fragment DataGroupParts on DataGroup {
    id
    name
    description
    createdAt
}

fragment CellParts on Cell {
    id
    name
    description
    createdAt
    dGroup
}

fragment CultureParts on Culture {
    id
    name
    description
    createdAt
    dGroup
}

fragment CellCultureParts on CellCulturePair {
    cell {
        ...CellParts
    }
    culture {
        ...CultureParts
    }
    createdAt
    dGroup {
        ...DataGroupParts
    }
}
