query GetCellCulturesPairs($fetchOptions: CellCulturePairFetchOptions!) {
    cellCulturePairs(fetchOptions: $fetchOptions) {
        total
        page
        limit
        results {
            ...CellCultureParts
        }
    }
}

query GetAllCellCulturePairs($fetchOptions: CellCulturePairFetchOptions!) {
    getAllCellCulturePairs(fetchOptions: $fetchOptions) {
        total
        results {
            ...CellCultureParts
        }
    }
}


query GetCellCulturePair($fetchOptions: CellCulturePairFetchOptions!) {
    cellCulture(fetchOptions: $fetchOptions) {
        ...CellCultureParts
    }
}

mutation InsertCellCulturePair($insertOptions: CellCulturePairInsertOptions!) {
    insertCellCulturePair(insertOptions: $insertOptions) {
        ...CellCultureParts
    }
}

mutation UpdateCellCulturePair($updateOptions: CellCulturePairUpdateOptions!) {
    updateCellCulturePair(updateOptions: $updateOptions) {
        ...CellCultureParts
    }
}

mutation DeleteCellCulturePair($deleteOptions: CellCulturePairDeleteOptions!) {
  deleteCellCulturePair(deleteOptions: $deleteOptions) {
    ...CellCultureParts
  }
}

fragment DataGroupParts on DataGroup {
    id
    name
    description
    createdAt
}

fragment CellParts on Cell {
    id
    name
    description
    createdAt
    dGroup {
        ...DataGroupParts
    }
}

fragment CultureParts on Culture {
    id
    name
    description
    createdAt
    dGroup {
        ...DataGroupParts
    }
}

fragment CellCultureParts on CellCulturePair {
    cell {
        ...CellParts
    }
    culture {
        ...CultureParts
    }
    createdAt
    dGroup {
        ...DataGroupParts
    }
}
