query GetCultures($options: CultureFetchOptions!) {
    cultures(options: $options) {
        page
        pageSize
        totalItems
        totalPages
        results {
            ...CultureParts
        }
    }
}

query GetUnpairedCultures($options: CultureParityFetchOptions!) {
    unpairedCultures(options: $options) {
        page
        pageSize
        totalItems
        totalPages
        results {
            ...CultureParts
        }
    }
}

query GetPairedCultures($options: CultureParityFetchOptions!) {
    pairedCultures(options: $options) {
        page
        pageSize
        totalItems
        totalPages
        results {
            ...CultureParts
        }
    }
}

mutation InsertCulture($options: CultureInsertOptions!) {
    insertCulture(options: $options) {
        ...CultureParts
    }
}

mutation UpdateCulture($options: CultureUpdateOptions!) {
    updateCulture(options: $options) {
        ...CultureParts
    }
}

mutation DeleteCulture($options: DeleteOptions!) {
    deleteCulture(options: $options) {
        numRows
    }
}

fragment CultureParts on Culture {
    id
    name
    description
    createdAt
    dGroup
}
