query GetCultures($options: CultureFetchOptions!) {
    cultures(options: $options) {
        page
        pageSize
        totalItems
        totalPages
        results {
            ...CultureParts
        }
    }
}

query GetUnpairedCultures($options: CultureParityFetchOptions!) {
    unpairedCultures(options: $options) {
        page
        pageSize
        totalItems
        totalPages
        results {
            ...CultureParts
        }
    }
}

query GetPairedCultures($options: CultureParityFetchOptions!) {
    pairedCultures(options: $options) {
        page
        pageSize
        totalItems
        totalPages
        results {
            ...CultureParts
        }
    }
}

mutation InsertCulture($insertOptions: CultureInsertOptions!) {
    insertCulture(options: $insertOptions) {
        ...CultureParts
    }
}

mutation UpdateCulture($updateOptions: CultureUpdateOptions!) {
    updateCulture(options: $updateOptions) {
        ...CultureParts
    }
}

mutation DeleteCulture($deleteOptions: DeleteOptions!) {
    deleteCulture(options: $deleteOptions) {
        numRows
    }
}

fragment CultureParts on Culture {
    id
    name
    description
    createdAt
    dGroup
}
