query GetCultures($fetchOptions: CultureFetchOptions!) {
    cultures(fetchOptions: $fetchOptions) {
        total
        page
        limit
        results {
            ...CultureParts
        }
    }
}

query GetCulture($fetchOptions: CultureFetchOptions!) {
    culture(fetchOptions: $fetchOptions) {
        ...CultureParts
    }
}

query GetUnpairedCultures($fetchOptions: CultureFetchUnpairedOptions!) {
    unpairedCultures(fetchOptions: $fetchOptions) {
        total
        page
        limit
        results {
            ...CultureParts
        }
    }
}

query GetPairedCultures($fetchOptions: CultureFetchUnpairedOptions!) {
    pairedCultures(fetchOptions: $fetchOptions) {
        total
        page
        limit
        results {
            ...CultureParts
        }
    }
}

mutation InsertCulture($insertOptions: CultureInsertOptions!) {
    insertCulture(insertOptions: $insertOptions) {
        ...CultureParts
    }
}

mutation UpdateCulture($updateOptions: CultureUpdateOptions!) {
    updateCulture(updateOptions: $updateOptions) {
        ...CultureParts
    }
}

mutation DeleteCulture($deleteOptions: DeleteOptions!) {
    deleteCulture(deleteOptions: $deleteOptions) {
        ...CultureParts
    }
}

fragment CultureParts on Culture {
    id
    name
    description
    createdAt
}
