query GetDataGroups($options: DataGroupFetchOptions!) {
    dataGroups(options: $options) {
        page
        pageSize
        totalItems
        totalPages
        results {
            ...DataGroupParts
        }
    }
}


mutation InsertDataGroup($options: DataGroupInsertOptions!) {
    insertDataGroup(options: $options) {
        ...DataGroupParts
    }
}

mutation UpdateDataGroup($options: DataGroupUpdateOptions!) {
    updateDataGroup(options: $options) {
        ...DataGroupParts
    }
}

mutation DeleteDataGroup($options: DeleteOptions!) {
    deleteDataGroup(options: $options) {
        numRows
    }
}

fragment DataGroupParts on DataGroup {
    id
    name
    description
    createdAt
}
