query GetDataGroups {
    dataGroups {
        idMbeGroup
        ...DataGroupParts
    }
}

mutation InsertDataGroup($insertOptions: DataGroupInsertOptions!) {
    insertDataGroup(options: $insertOptions) {
        idMbeGroup
        ...DataGroupParts
    }
}

mutation UpdateDataGroup($updateOptions: DataGroupUpdateOptions!) {
    updateDataGroup(options: $updateOptions) {
        idMbeGroup
        ...DataGroupParts
    }
}

mutation DeleteDataGroup($deleteOptions: DeleteOptions!) {
    deleteDataGroup(options: $deleteOptions) {
        numRows
    }
}

fragment DataGroupParts on DataGroup {
    id
    name
    description
    createdAt
}
