query GetEntries($fetchOptions: EntryFetchOptions!) {
    entries(fetchOptions: $fetchOptions) {
        total
        page
        limit
        results {
            ...EntryParts
        }
    }
}

query GetAllEntries($fetchOptions: EntryFetchOptions!) {
     getAllEntries(fetchOptions: $fetchOptions) {
        total
        results {
            ...EntryParts
        }
    }
}

query GetEntry($fetchOptions: EntryFetchOptions!) {
    entry(fetchOptions: $fetchOptions) {
        ...EntryParts
    }
}

query GetEntryGroups($fetchGroupOptions: EntryGroupFetchOptions!) {
    getEntryGroups(fetchOptions: $fetchGroupOptions) {
        total
        page
        limit
        results {
            id
            name
        }
    }
}

mutation InsertEntry($insertOptions: EntryInsertOptions!) {
    insertEntry(insertOptions: $insertOptions) {
        ...EntryParts
    }
}

mutation UpdateEntry($updateOptions: EntryUpdateOptions!) {
    updateEntry(updateOptions: $updateOptions) {
        ...EntryParts
    }
}

mutation DeleteEntry($deleteOptions: DeleteOptions!) {
  deleteEntry(deleteOptions: $deleteOptions) {
    ...EntryParts
  }
}

fragment DataGroupParts on DataGroup {
    id
    name
    description
    createdAt
}

fragment CellParts on Cell {
    id
    name
    description
    createdAt
    dGroup {
        ...DataGroupParts
    }
}

fragment CultureParts on Culture {
    id
    name
    description
    createdAt
    dGroup {
        ...DataGroupParts
    }
}

fragment CellCultureParts on CellCulturePair {
    cell {
        ...CellParts
    }
    culture {
        ...CultureParts
    }
    createdAt
    dGroup {
        ...DataGroupParts
    }
}

fragment BuyerParts on Buyer {
    id
    name
    address
    contact
    createdAt
    dGroup {
        ...DataGroupParts
    }
}

fragment EntryParts on Entry {
    id
    weight
    weightType
    date
    createdAt
    buyer {
        ...BuyerParts
    }
    cellCulturePair {
        ...CellCultureParts
    }
    dGroup {
        ...DataGroupParts
    }
}
