query GetEntries($fetchOptions: EntryFetchOptions!) {
    entries(fetchOptions: $fetchOptions) {
        total
        page
        limit
        results {
            ...EntryParts
        }
    }
}

query GetAllEntries($fetchOptions: EntryFetchOptions!) {
     getAllEntries(fetchOptions: $fetchOptions) {
        total
        results {
            ...EntryParts
        }
    }
}

query GetEntry($fetchOptions: EntryFetchOptions!) {
    entry(fetchOptions: $fetchOptions) {
        ...EntryParts
    }
}

query GetEntryGroups($fetchOptions: EntryGroupFetchOptions!) {
    getEntryGroups(fetchOptions: $fetchOptions) {
        total
        page
        limit
        results {
            id
            name
        }
    }
}

mutation InsertEntry($insertOptions: EntryInsertOptions!) {
    insertEntry(insertOptions: $insertOptions) {
        ...EntryParts
    }
}

mutation UpdateEntry($updateOptions: EntryUpdateOptions!) {
    updateEntry(updateOptions: $updateOptions) {
        ...EntryParts
    }
}

mutation DeleteEntry($deleteOptions: DeleteOptions!) {
  deleteEntry(deleteOptions: $deleteOptions) {
    ...EntryParts
  }
}

fragment EntryParts on Entry {
    id
    weight
    weightType
    date
    createdAt
    buyer {
        ...BuyerParts
    }
    cellCulturePair {
        ...CellCultureParts
    }
    dGroup {
        ...DataGroupParts
    }
}
