query GetEntries($options: EntryFetchOptions!) {
    entries(options: $options) {
        page
        pageSize
        totalItems
        totalPages
        results {
            ...EntryParts
        }
    }
}

query GetAllEntries($options: EntryFetchOptions!) {
     allEntries(options: $options) {
        total
        results {
            ...EntryParts
        }
    }
}

mutation InsertEntry($options: EntryInsertOptions!) {
    insertEntry(options: $options) {
        ...EntryParts
    }
}

mutation UpdateEntry($options: EntryUpdateOptions!) {
    updateEntry(options: $options) {
        ...EntryParts
    }
}

mutation DeleteEntry($options: DeleteOptions!) {
    deleteEntry(options: $options) {
        numRows
    }
}

fragment DataGroupParts on DataGroup {
    id
    name
    description
    createdAt
}

fragment CellParts on Cell {
    id
    name
    description
    createdAt
    dGroup
}

fragment CultureParts on Culture {
    id
    name
    description
    createdAt
    dGroup
}

fragment CellCultureParts on CellCulturePair {
    cell {
        ...CellParts
    }
    culture {
        ...CultureParts
    }
    createdAt
    dGroup {
        ...DataGroupParts
    }
}

fragment BuyerParts on Buyer {
    id
    name
    address
    contact
    createdAt
    dGroup
}

fragment EntryParts on Entry {
    id
    weight
    weightType
    date
    createdAt
    buyer {
        ...BuyerParts
    }
    cell {
        ...CellParts
    }
    culture {
        ...CultureParts
    }
    dGroup {
        ...DataGroupParts
    }
}
