mutation InsertMbeGroupMember($options: MbeGroupMembersOptions!) {
    insertGroupMember(options: $options) {
        idMbeUser
        idMbeGroup
    }
}

mutation RemoveMbeGroupMember($options: MbeGroupMembersOptions!) {
    removeGroupMember(options: $options) {
        numRows
    }
}
