//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.7

use async_trait::async_trait;
use sea_orm::{ConnectionTrait, EntityTrait, PaginatorTrait};

pub mod prelude;

pub mod buyer;
pub mod cell;
pub mod cell_culture_pair;
pub mod culture;
pub mod data_group;
pub mod entry;
pub mod weight_types;
